name: Validate

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        include:
          - os: macos-latest
            command: ".github/workflows/val.sh"
          - os: ubuntu-latest
            command: ".github/workflows/val.sh"
            chmod: true
          - os: windows-latest
            command: ".github/workflows/val.bat"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up MinGW
      uses: mingw-w64-x86_64-toolchain
      with:
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest' }}
    - name: Build
      run: make -j
    - name: Validate
      run: |
        chmod +x .github/workflows/val.sh
        ${{ matrix.command }}

