name: Validate

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        include:
          - os: windows-latest
            command: ".github/workflows/val.bat"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git mingw-w64-x86_64-zlib
    - name: Build
      run: make -j
    - name: Validate
      run: |
        chmod +x .github/workflows/val.sh
        ${{ matrix.command }}

