name: Validate

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        include:
          - os: macos-latest
            command: ".github/workflows/val.sh"
            shell: bash
          - os: ubuntu-latest
            command: ".github/workflows/val.sh"
            shell: bash
          - os: windows-latest
            command: ".github/workflows/val.bat"
            shell: cmd
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Validate
      run: |
        chmod +x .github/workflows/val.sh
        ${{ matrix.command }}
      shell: ${{ matrix.shell }}

