name: Validate

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        include:
          - os: macos-latest
            command: "build/bin/gfastats-validate validateFiles -v"
          - os: ubuntu-latest
            command: "build/bin/gfastats-validate validateFiles -v"
          - os: windows-latest
            command: "./val"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Validate
      run: ${{ matrix.command }}
