name: Validate

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        include:

          - os: windows-latest
            command: ".github/workflows/val.bat"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: install zlib
      uses: msys2/setup-msys2@v2
      with:
        install: zlib
    - name: Build
      run: make
    - name: Validate
      run: |
        chmod +x .github/workflows/val.sh
        ${{ matrix.command }}

