name: Validate

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validate
    strategy:
      matrix:
        OS: [macos-latest, ubuntu-latest, windows-latest]
        include:
        - OS: macos-latest
          CMD: build/bin/gfastats-validate validateFiles -v
        - OS: ubuntu-latest
          CMD: build/bin/gfastats-validate validateFiles -v
        - OS: windows-latest
          CMD: "build/bin/gfastats-validate.exe" validateFiles -v
    runs-on: ${{ matrix.OS }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Validate
      run: ${{ matrix.CMD }}
